status = [
    "Rustfmt",
    "Clippy",
    "MSRV",
    "Prepare Tests",
    "Tests (routes::eval::test::assembly_as)",
    "Tests (routes::eval::test::assembly_nasm)",
    "Tests (routes::eval::test::bash)",
    "Tests (routes::eval::test::befunge)",
    "Tests (routes::eval::test::c)",
    "Tests (routes::eval::test::cpp)",
    "Tests (routes::eval::test::crystal)",
    "Tests (routes::eval::test::csharp)",
    "Tests (routes::eval::test::deno)",
    "Tests (routes::eval::test::elixir)",
    "Tests (routes::eval::test::erlang)",
    "Tests (routes::eval::test::fsharp)",
    "Tests (routes::eval::test::go)",
    "Tests (routes::eval::test::haskell)",
    "Tests (routes::eval::test::java)",
    "Tests (routes::eval::test::javascript)",
    "Tests (routes::eval::test::julia)",
    "Tests (routes::eval::test::lolcode)",
    "Tests (routes::eval::test::lua)",
    "Tests (routes::eval::test::perl)",
    "Tests (routes::eval::test::php)",
    "Tests (routes::eval::test::python)",
    "Tests (routes::eval::test::ruby)",
    "Tests (routes::eval::test::rust)",
    "Tests (routes::eval::test::shakespeare)",
    "Tests (routes::eval::test::typescript)"
]
